Tildes y Typos arreglados en el post
lualfemo/Hyperblog.github.io pull request #1
Opened 2022-02-01 17:37 UTC by lualfemo

No debimos pasar este error.

2022-02-01 18:00 UTC, lualfemo1 requested changes
En vez de usar tildes directas, usa entidades HTML.

2022-02-02 12:11 UTC, lualfemo commented
Cambios hechos, por favor haz el merge.

2022-02-02 12:13 UTC, lualfemo commented
Cambios hechos, por favor haz el merge.

2022-02-02 12:15 UTC, lualfemo1 approved these changes
Excelente

2022-02-02 12:27 UTC, merged